input_pcd: ""
output_directory: /tmp/jiangyin_map/permanent
map_name: competition_map
odom_topic: /Odometry_lio_global
initialized_topic: /relocalization/initialized
state_topic: /map_origin_setter/state
input_frame: unanchored_lio_local
output_frame: lio_global
output_leaf_size: 0.05
require_stationary: true
max_linear_speed: 0.05
max_angular_speed: 0.03
