wait_time: 15.0  # 发布前三个航点后，等待的墙钟时间（秒）

# yaw 单位为 rad；使用 .nan 表示不固定终端 yaw。
# desired_speed 单位为 m/s；小于或等于 0 时，规划器将终端速度设为 0。
# mode: 0=默认速度，1=正常速度，2=慢速。
# is_map: 1=启用避障，0=关闭避障。
waypoints:
  # - {id: 0, x: 1.0,  y: 1.0,   z: 1.0, mode: 1, is_map: 1, yaw: 0, desired_speed: 0.0}
  # - {id: 1, x: 11.4, y: 2.6,   z: 1.0, mode: 1, is_map: 1, yaw: 1.5708, desired_speed: 0.0}
  # - {id: 2, x: 11.4, y: 4.9,   z: 1.0, mode: 1, is_map: 1, yaw: 4.7124, desired_speed: 0.0}
  # - {id: 3, x: 11.4, y: 4.9,   z: 1.0, mode: 1, is_map: 1, yaw: 1.5708, desired_speed: 0.0}
  # - {id: 4, x: 7.0,  y: 11.25, z: 1.0, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  # - {id: 5, x: 3.7,  y: 13.6,  z: 1.5, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  # - {id: 6, x: 2.7,  y: 13.0,  z: 1.5, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  # - {id: 7, x: 2.7,  y: 13.0,  z: 0.5, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  # - {id: 8, x: 2.0,  y: 12.4,  z: 0.5, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  # - {id: 9, x: 1.0,  y: 14.0,  z: 1.0, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}

  - {id: 0, x: 1.0,  y: 1.0,   z: 1.0, mode: 1, is_map: 1, yaw: 0, desired_speed: 0.0}
  - {id: 1, x: 11.4, y: 2.6,   z: 1.0, mode: 1, is_map: 1, yaw: 1.5708, desired_speed: 0.0}
  - {id: 2, x: 11.4, y: 4.9,   z: 1.0, mode: 1, is_map: 1, yaw: 4.7124, desired_speed: 0.0}
  - {id: 3, x: 7.0,  y: 11.25, z: 1.0, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  - {id: 4, x: 3.7,  y: 13.6,  z: 1.5, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  - {id: 5, x: 2.7,  y: 13.0,  z: 1.5, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  - {id: 6, x: 2.7,  y: 13.0,  z: 0.5, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  - {id: 7, x: 2.0,  y: 12.4,  z: 0.5, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
  - {id: 8, x: 1.0,  y: 14.0,  z: 1.0, mode: 1, is_map: 1, yaw: 3.1416, desired_speed: 0.0}
