FROM docker.io/osrf/ros:noetic-desktop-full

ENV DEBIAN_FRONTEND=noninteractive

COPY dist/debs/ /tmp/jiangyin-debs/

RUN apt-get update && apt-get install -y --no-install-recommends \
    coinor-libipopt-dev \
    libeigen3-dev \
    libomp-dev \
    && apt-get install -y /tmp/jiangyin-debs/*.deb \
    && rm -rf /var/lib/apt/lists/* /tmp/jiangyin-debs

WORKDIR /ws
CMD ["bash"]

