ARG ROS_BASE_IMAGE=docker.io/osrf/ros:noetic-desktop-full
FROM ${ROS_BASE_IMAGE} AS build-base

ARG ROS_BASE_IMAGE
ARG CASADI_COMMIT=f959d3175a444d763e4eda4aece48f4c5f4a6f90
ARG BUILD_JOBS=4
ARG LIVOX_SDK2_COMMIT=master
ARG LIVOX_ROS_DRIVER2_COMMIT=13eb05e4e6dd7a765b934d0c5fd6236676a57b49
ARG SOPHUS_COMMIT=49c07cca02c80781274c25d39e4f1f28c9092e03

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get -o Acquire::http::Timeout=30 -o Acquire::Retries=5 update \
    && apt-get -o Acquire::http::Timeout=30 -o Acquire::Retries=5 install -y --no-install-recommends \
    build-essential \
    cmake \
    coinor-libipopt-dev \
    dpkg-dev \
    gfortran \
    git \
    liblapack-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

FROM build-base AS casadi-build

ARG CASADI_COMMIT=f959d3175a444d763e4eda4aece48f4c5f4a6f90
ARG BUILD_JOBS=4

RUN git init casadi \
    && git -C casadi remote add origin https://github.com/casadi/casadi.git \
    && git -C casadi fetch --depth 1 origin "${CASADI_COMMIT}" \
    && git -C casadi checkout --detach FETCH_HEAD \
    && cmake -S casadi -B casadi/build \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_IPOPT=ON \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
    && cmake --build casadi/build --parallel "${BUILD_JOBS}" \
    && DESTDIR=/pkg/casadi cmake --install casadi/build

COPY docker/tests/casadi_ipopt_smoke.cpp /tmp/casadi_ipopt_smoke.cpp
RUN g++ -std=c++14 /tmp/casadi_ipopt_smoke.cpp \
      -I/pkg/casadi/usr/local/include \
      -L/pkg/casadi/usr/local/lib \
      -Wl,-rpath,/pkg/casadi/usr/local/lib \
      -lcasadi \
      -o /tmp/casadi_ipopt_smoke \
    && LD_LIBRARY_PATH=/pkg/casadi/usr/local/lib /tmp/casadi_ipopt_smoke

FROM casadi-build AS casadi-deb

COPY docker/build-debs.sh /usr/local/bin/build-jiangyin-debs
RUN chmod +x /usr/local/bin/build-jiangyin-debs \
    && build-jiangyin-debs /pkg /out/debs casadi

FROM casadi-build AS full-build

ARG BUILD_JOBS=4
ARG LIVOX_SDK2_COMMIT=master
ARG LIVOX_ROS_DRIVER2_COMMIT=13eb05e4e6dd7a765b934d0c5fd6236676a57b49
ARG SOPHUS_COMMIT=49c07cca02c80781274c25d39e4f1f28c9092e03

RUN apt-get -o Acquire::http::Timeout=30 -o Acquire::Retries=5 update \
    && apt-get -o Acquire::http::Timeout=30 -o Acquire::Retries=5 install -y --no-install-recommends \
    libapr1-dev \
    libeigen3-dev \
    ros-noetic-message-generation \
    ros-noetic-pcl-ros \
    ros-noetic-rosbag \
    ros-noetic-rospy \
    && rm -rf /var/lib/apt/lists/*

RUN git init Livox-SDK2 \
    && git -C Livox-SDK2 remote add origin https://github.com/Livox-SDK/Livox-SDK2.git \
    && git -C Livox-SDK2 fetch --depth 1 origin "${LIVOX_SDK2_COMMIT}" \
    && git -C Livox-SDK2 checkout --detach FETCH_HEAD \
    && cmake -S Livox-SDK2 -B Livox-SDK2/build \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
    && cmake --build Livox-SDK2/build --parallel "${BUILD_JOBS}" \
    && cmake --install Livox-SDK2/build \
    && DESTDIR=/pkg/livox cmake --install Livox-SDK2/build

RUN mkdir -p livox-ws/src \
    && git init livox-ws/src/livox_ros_driver2 \
    && git -C livox-ws/src/livox_ros_driver2 remote add origin https://github.com/Livox-SDK/livox_ros_driver2.git \
    && git -C livox-ws/src/livox_ros_driver2 fetch --depth 1 origin "${LIVOX_ROS_DRIVER2_COMMIT}" \
    && git -C livox-ws/src/livox_ros_driver2 checkout --detach FETCH_HEAD \
    && cp livox-ws/src/livox_ros_driver2/package_ROS1.xml livox-ws/src/livox_ros_driver2/package.xml \
    && /bin/bash -c 'source /opt/ros/noetic/setup.bash \
      && cd /build/livox-ws \
      && catkin_init_workspace src \
      && catkin_make -j${BUILD_JOBS} -DROS_EDITION=ROS1 -DCMAKE_INSTALL_PREFIX=/opt/ros/noetic \
      && DESTDIR=/pkg/livox-ros-driver2 cmake --build build --target install --parallel ${BUILD_JOBS} \
      && find /pkg/livox-ros-driver2/opt/ros/noetic -mindepth 1 -maxdepth 1 \
        ! -name include ! -name lib ! -name share -exec rm -rf {} +'

RUN git init Sophus \
    && git -C Sophus remote add origin https://github.com/strasdat/Sophus.git \
    && git -C Sophus fetch --depth 1 origin "${SOPHUS_COMMIT}" \
    && git -C Sophus checkout --detach FETCH_HEAD \
    && cmake -S Sophus -B Sophus/build \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SOPHUS_EXAMPLES=OFF \
      -DBUILD_SOPHUS_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
    && cmake --build Sophus/build --parallel "${BUILD_JOBS}" \
    && DESTDIR=/pkg/sophus cmake --install Sophus/build

COPY docker/build-debs.sh /usr/local/bin/build-jiangyin-debs
RUN chmod +x /usr/local/bin/build-jiangyin-debs \
    && build-jiangyin-debs /pkg /out/debs
