#!/usr/bin/env python3

import math
import os
import sys
import threading
import time

import rospy
from geometry_msgs.msg import PoseStamped


def yaw_from_quaternion(q):
    return math.atan2(
        2.0 * (q.w * q.z + q.x * q.y),
        1.0 - 2.0 * (q.y * q.y + q.z * q.z),
    )


class SuperWaypointRecorder:
    def __init__(self):
        self._lock = threading.Lock()
        self._latest_pose = None

        self._pose_topic = rospy.get_param(
            "~pose_topic", "/mavros/local_position/pose")
        self._output_file = rospy.get_param(
            "~output_file",
            os.path.expanduser("~/mission_super_waypoints.yaml"))
        self._mode = int(rospy.get_param("~mode", 2))
        self._is_map = int(rospy.get_param("~is_map", 1))
        self._desired_speed = float(rospy.get_param("~desired_speed", 0.0))
        self._frame_id = rospy.get_param("~frame_id", "world")
        self._segment_count = int(rospy.get_param("~segment_count", 3))
        self._current_segment = int(rospy.get_param("~start_segment", 1)) - 1
        self._segments = [[] for _ in range(self._segment_count)]

        if self._mode not in (0, 1, 2):
            raise ValueError("~mode must be 0, 1, or 2")
        if self._is_map not in (0, 1):
            raise ValueError("~is_map must be 0 or 1")
        if not math.isfinite(self._desired_speed) or self._desired_speed < 0.0:
            raise ValueError("~desired_speed must be finite and non-negative")
        if self._segment_count <= 0:
            raise ValueError("~segment_count must be positive")
        if self._current_segment < 0 or self._current_segment >= self._segment_count:
            raise ValueError("~start_segment must be in [1, ~segment_count]")

        rospy.Subscriber(self._pose_topic, PoseStamped, self._pose_callback,
                         queue_size=10)

    def _pose_callback(self, message):
        with self._lock:
            self._latest_pose = message

    def _snapshot_pose(self):
        with self._lock:
            return self._latest_pose

    def _add_waypoint(self):
        pose = self._snapshot_pose()
        if pose is None:
            rospy.logwarn("No pose received yet from %s", self._pose_topic)
            return

        p = pose.pose.position
        yaw = yaw_from_quaternion(pose.pose.orientation)
        segment = self._segments[self._current_segment]
        waypoint = {
            "id": len(segment),
            "x": p.x,
            "y": p.y,
            "z": p.z,
            "mode": self._mode,
            "is_map": self._is_map,
            "yaw": yaw,
            "desired_speed": self._desired_speed,
        }
        segment.append(waypoint)
        self._write_file()
        rospy.loginfo(
            "Recorded segment %d waypoint %d: x=%.3f y=%.3f z=%.3f yaw=%.3f",
            self._current_segment + 1, waypoint["id"], waypoint["x"],
            waypoint["y"], waypoint["z"], waypoint["yaw"])

    def _undo(self):
        segment = self._segments[self._current_segment]
        if not segment:
            rospy.logwarn("No waypoint to undo in segment %d",
                          self._current_segment + 1)
            return
        waypoint = segment.pop()
        self._write_file()
        rospy.loginfo("Removed segment %d waypoint %d",
                      self._current_segment + 1, waypoint["id"])

    def _set_segment(self, segment_number):
        index = segment_number - 1
        if index < 0 or index >= self._segment_count:
            rospy.logwarn("Segment must be in [1, %d]", self._segment_count)
            return
        self._current_segment = index
        rospy.loginfo("Current segment: %d", self._current_segment + 1)

    def _next_segment(self):
        self._set_segment(min(self._segment_count, self._current_segment + 2))

    def _previous_segment(self):
        self._set_segment(max(1, self._current_segment))

    def _total_waypoint_count(self):
        return sum(len(segment) for segment in self._segments)

    def _write_file(self):
        directory = os.path.dirname(os.path.abspath(self._output_file))
        if directory:
            os.makedirs(directory, exist_ok=True)

        with open(self._output_file, "w", encoding="utf-8") as handle:
            handle.write("# Generated by fsm_ctrl record_super_waypoints.py\n")
            handle.write("# yaw unit: rad. SML publishes one waypoint per tick.\n")
            handle.write("# cmd3 uses segment 1, cmd4 segment 2, cmd5 segment 3.\n")
            handle.write("frame_id: \"{}\"\n".format(self._frame_id))
            handle.write("segments:\n")
            for segment_index, segment in enumerate(self._segments):
                handle.write("  - name: \"cmd{}_segment_{}\"\n".format(
                    segment_index + 3, segment_index + 1))
                if not segment:
                    handle.write("    waypoints: []\n")
                    continue
                handle.write("    waypoints:\n")
                for index, waypoint in enumerate(segment):
                    waypoint["id"] = index
                    handle.write(
                        "      - {{id: {id}, x: {x:.6f}, y: {y:.6f}, "
                        "z: {z:.6f}, mode: {mode}, is_map: {is_map}, "
                        "yaw: {yaw:.6f}, "
                        "desired_speed: {desired_speed:.6f}}}\n".format(
                            **waypoint))

    def run(self):
        rospy.loginfo("Recording pose from %s", self._pose_topic)
        rospy.loginfo("Writing waypoints to %s", self._output_file)
        rospy.loginfo("Current segment: %d/%d", self._current_segment + 1,
                      self._segment_count)
        rospy.loginfo(
            "Commands: Enter/a add, seg N switch, n next, p previous, "
            "u undo, s save, q quit")

        while not rospy.is_shutdown():
            try:
                command = input("> ").strip().lower()
            except EOFError:
                break
            if command in ("", "a", "add"):
                self._add_waypoint()
            elif command in ("u", "undo"):
                self._undo()
            elif command in ("n", "next"):
                self._next_segment()
            elif command in ("p", "prev", "previous"):
                self._previous_segment()
            elif command.startswith("seg "):
                try:
                    self._set_segment(int(command.split()[1]))
                except (IndexError, ValueError):
                    rospy.logwarn("Usage: seg N")
            elif command in ("s", "save"):
                self._write_file()
                rospy.loginfo("Saved %d waypoints in %d segments",
                              self._total_waypoint_count(),
                              self._segment_count)
            elif command in ("q", "quit", "exit"):
                self._write_file()
                rospy.loginfo("Saved %d waypoints in %d segments and exiting",
                              self._total_waypoint_count(),
                              self._segment_count)
                break
            else:
                rospy.logwarn("Unknown command '%s'", command)
            time.sleep(0.01)


def main():
    rospy.init_node("record_super_waypoints")
    try:
        recorder = SuperWaypointRecorder()
        recorder.run()
    except Exception as error:
        rospy.logerr("%s", error)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
